services:
  basler-camera-service:
    # container / image
    container_name: camera-adapter
    build:
      context: ./
      dockerfile: BaslerCameraAdapter.Dockerfile
    image: maxscw/basler-camera-adapter
    # restart policy
    restart: unless-stopped
    stop_signal: SIGTERM  # optional: ensures a graceful stop
    # customization
    environment:
      - TZ=Europe/Berlin
      # customize
      - LOGGING_LEVEL=DEBUG
      - FRAMES_PER_SECOND=15
#      - TEST_IMAGE_PATH=/home/app/test/*.png
#    volumes:
#      - ./testimages:/home/app/test
    ports:
      - 3956:3956
      - 46000:46000/udp  # set Streaming Port to fixed value with pylonViewer
      - 5005:5050  # external access port | for debugging