version: "3"

services:
  basler-camera-service:
    # container / image
    container_name: camera-adapter
    build:
      context: ./
      dockerfile: BaslerCameraAdapter.Dockerfile
    image: maxscw/basler-camera-adapter
    # restart policy
    restart: unless-stopped
    # customization
    environment:
      - TZ=Europe/Berlin
      # customize
      - LOGGING_LEVEL=DEBUG
      - TEST_IMAGE_PATH=/home/app/testimages/*.bmp
    volumes:
      - ./testimages:/home/app/testimages
    ports:
      - 3956:3956
      - 46000:46000/udp  # set Streaming Port to fixed value with pylonViewer
      - 5005:5050  # external access port | for debugging